### ISSUE TITLE
Corrupted tab decorations related to Firefox

### ISSUE THREAD

**Issue by postsolar** [outfoxxed/hy3#38]
hyprland-nvidia-git v0.30.0-40-g9ec656a3
hy3 0.30 downloaded from the releases page and built from source
default hy3 config copied from the readme

Tab decorations in tab bars become corrupted when 1) the last opened (or focused?) window in a group is Firefox AND 2) the focus is on/inside the group.

to reproduce:

- open a ff window, make it a tabs group
- open a new ff window, see defects
- focus on a window outside of the tabs group, defects gone
- focus back in, defects are back
- open anything other than ff in a new tab, defects are gone
- open yet another tab, again with ff, defects are back

edit: I noticed it only takes place if window titles' display is enabled. when it's turned off it's all good.

**Comment by outfoxxed** [comment]
was this fixed with 0862855?

**Comment by postsolar** [comment]
> was this fixed with https://github.com/outfoxxed/hy3/commit/0862855b8709a63cf92210f56d31a71df105e273?

Build with yay fails

<details>
<summary>Details</summary>

```
==> Making package: hy3-git r209.65a849b-3 (Thu 02 Nov 2023 09:05:50 PM EET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating hy3 git repo...
==> Validating source files with sha256sums...
    hy3 ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of hy3 git repo...
Cloning into 'hy3'...
done.
==> Starting pkgver()...
==> Updated version: hy3-git r214.352419b-1
==> Sources are ready.
==> Making package: hy3-git r214.352419b-1 (Thu 02 Nov 2023 09:05:53 PM EET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
-- Checking for modules 'hyprland;pixman-1;libdrm;pango;pangocairo'
--   Found hyprland, version 0.31.0
--   Found pixman-1, version 0.42.2
--   Found libdrm, version 2.4.116
--   Found pango, version 1.51.0
--   Found pangocairo, version 1.51.0
-- Configuring done (0.7s)
-- Generating done (0.0s)
-- Build files have been written to: /home/me/.cache/yay/hy3-git/src/build
[ 14%] Building CXX object CMakeFiles/hy3.dir/src/main.cpp.o
In file included from /usr/include/hyprland/src/helpers/Vector2D.hpp:5,
                 from /usr/include/hyprland/src/includes.hpp:147,
                 from /usr/include/hyprland/src/defines.hpp:1,
                 from /usr/include/hyprland/src/Compositor.hpp:7,
                 from /home/me/.cache/yay/hy3-git/src/hy3/src/main.cpp:3:
/usr/include/hyprland/src/macros.hpp:17:10: fatal error: version.h: No such file or directory
   17 | #include "version.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/hy3.dir/build.make:76: CMakeFiles/hy3.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/hy3.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: hy3-git-exit status 4
 -> devel check for package failed: '/usr/bin/git ls-remote https://github.com/hyprwm/Hyprland.git HEAD' encountered an error: fatal: Unable to read current working directory: No such file or directory
 -> Failed to install the following packages. Manual intervention is required:
hy3-git - exit status 4

```

</details>

**Comment by outfoxxed** [comment]
mismatched headers, you'll have to clear some files out and reinstall probably (listed in readme)

**Comment by postsolar** [comment]
Ran it twice, still the same. My prefix for headers and pkg-config was `/usr/`.

**Comment by outfoxxed** [comment]
try master

**Comment by postsolar** [comment]
same thing. I guess it's more of a hyprland issue? if I open `/usr/include/hyprland/src/macros.hpp` the lsp is telling me it can't find `version.h`. should I open an issue in hyprland repo?

**Comment by outfoxxed** [comment]
This is definitely something on your end.
I'm assuming you updated hyprland too right?

**Comment by postsolar** [comment]
I did, after deleting the old headers and pkg-config, all is in the readme

**Comment by outfoxxed** [comment]
Nothing in /usr/local or .local either? I'm running latest hyprland and hy3 myself at the moment.

**Comment by postsolar** [comment]
`fd hy /usr/local/ ~/.local/` nothing relevant to hyprland

**Comment by postsolar** [comment]
https://github.com/hyprwm/Hyprland/issues/3733

**Comment by postsolar** [comment]
Ok so the install thing was this: https://aur.archlinux.org/packages/hyprland-nvidia-git#comment-941160
And re the tabs thing: yeah they're now mostly stable which is a big W 💪, but some defects still occur when the mouse pointer is moving inside the tab bar area (infrequently, maybe 1/5 times). Another issue is that the tab bar extends to the left of the window whenever it's the leftmost (or the only) window on the workspace.
![image](https://github.com/outfoxxed/hy3/assets/120750161/7fbb0c18-4b1d-451c-81c5-9c9757800d36)
 but this one was the case before the update too

**Comment by outfoxxed** [comment]
Alright, closing this issue. The width bug is something else.

**Comment by outfoxxed** [comment]
> https://user-images.githubusercontent.com/120750161/280258649-7fbb0c18-4b1d-451c-81c5-9c9757800d36.png

Can you link me your configuration and any steps to reproduce this btw? I've had it reported before and used to be able to reproduce it myself but I can't anymore.

**Comment by postsolar** [comment]
My guess is it's somehow related to adjusting for gap size.
To reproduce: open 2 windows on a blank workspace, make them tabbed, then move one right.

<details>
<summary>Config</summary>

```
# plugin = /usr/lib/libhy3.so
plugin = $config/../plugins/libhy3.so

exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'ArcDusk-cursors'
exec-once = hyprctl setcursor ArcDusk-cursors 24

# $toggle_bar = killall waybar || waybar -c $config/waybar/waybar_config -s $config/waybar/waybar_styles
$toggle_bar = eww close bar -c $config/eww/ || eww open bar -c $config/eww/

source = $config/window_rules.conf
source = $config/keybinds.conf

# General
general {
  gaps_in = 10
  gaps_out = 35

  border_size = 3

  col.active_border = 0xff430825 0xffc794fb 30deg
  col.inactive_border = 0x33595959

  cursor_inactive_timeout = 1

  layout = hy3

  no_cursor_warps = yes
  no_focus_fallback = yes
  resize_on_border = yes
  extend_border_grab_area = 0
  hover_icon_on_border = no
}

plugin {
  hy3 {
    # policy controlling what happens when a node is removed from a group,
    # leaving only a group
    # 0 = remove the nested group
    # 1 = keep the nested group
    # 2 = keep the nested group only if its parent is a tab group
    # node_collapse_policy = <int> # default: 2
    node_collapse_policy = 1

    # offset from group split direction when only one window is in a group
    # group_inset = <int> # default: 10

    # tab group settings
    tabs {
      # height of the tab bar
      # height = <int> # default: 15
      # height = 14
      height = 4

      # padding between the tab bar and its focused node
      # padding = <int> # default: 5
      padding = 4

      # the tab bar should animate in/out from the top instead of below the window
      # from_top = <bool> # default: false

      # rounding of tab bar corners
      # rounding = <int> # default: 3
      rounding = 3

      # render the window title on the bar
      # render_text = <bool> # default: true
      render_text = no

      # TODO: Need to build MonoLisa with font features auto-enabled font to render the window title with

      # text_font = <string> # default: Sans
      # text_font = Recursive Sans Casual Static
      # text_font = JetBrains Mono NL SemiBold Italic
      # text_font = MonoLisa SemiBold Italic
      text_font = Victor Mono Bold Italic

      # height of the window title
      # text_height = <int> # default: 8
      text_height = 8

      # left padding of the window title
      # text_padding = <int> # default: 3
      text_padding = 5

      # active tab bar segment color
      # col.active = <color> # default: 0xff32b4ff
      col.active = 0xffb4195e

      # urgent tab bar segment color
      # col.urgent = <color> # default: 0xffff4f4f

      # inactive tab bar segment color
      # col.inactive = <color> # default: 0x80808080
      col.inactive = 0x55b4195e

      # active tab bar text color
      # col.text.active = <color> # default: 0xff000000

      # urgent tab bar text color
      # col.text.urgent = <color> # default: 0xff000000

      # inactive tab bar text color
      # col.text.inactive = <color> # default: 0xff000000
    }

    # autotiling settings
    autotile {
      enable = yes
    }
  }
}

# Decorations

decoration {

  blur {
    enabled = yes
    size = 4
    passes = 1
    ignore_opacity = no
    xray = yes
    noise = 0
    contrast = 2.0
  }

  rounding = 6

  active_opacity = 0.9
  inactive_opacity = 0.85
  fullscreen_opacity = 1

  dim_inactive = true
  # dim_strength = 0.15
  dim_strength = 0.25

  drop_shadow = yes
  shadow_range = 30
  shadow_render_power = 2
  # col.shadow = rgba(1a1a1aee)
  col.shadow = 0xdd3c1a3f
}

# Animations

animations {
  enabled = yes

  # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
  bezier = myBezier, 0.05, 0.9, 0.1, 1.05

  animation = windows, 1, 7, myBezier
  animation = windowsOut, 1, 7, default, popin 80%
  animation = border, 1, 10, default
  animation = borderangle, 1, 8, default
  animation = fade, 1, 7, default
  animation = workspaces, 1, 6, default
}

# Input

input {
  kb_layout = us,ru
  kb_variant =
  kb_model =
  # kb_options = grp:win_space_toggle,compose:rctrl
  kb_options = compose:rctrl
  kb_rules =

  numlock_by_default = yes

  follow_mouse = 2

  touchpad {
    natural_scroll = yes
    disable_while_typing = yes
    # drag_lock = yes
    drag_lock = no
  }

  # [-1.0 .. 1.0], 0 means no modification.
  sensitivity = 0.1
}

misc {
  # force_hypr_chan = yes
  animate_manual_resizes = yes
  animate_mouse_windowdragging = yes
}

binds {

}


```

</details>

**Comment by outfoxxed** [comment]
fixed in 91c94d6

**Comment by postsolar** [comment]
I still have it. Now there's a clear relationship between gaps size and the size of the extra bit which peeks outside: outer gaps proportionally increase this bit, whereas inner gaps proportionally decrease it

**Comment by outfoxxed** [comment]
Seeing as I can't reproduce either of your issues anymore and you just described the pre-fix behavior, I'm inclined to think you aren't actually updated for whatever reason. Run `hyprctl dispatch hy3:debugnodes` and send the message it prints starting with `DEBUG NODES`.

**Comment by postsolar** [comment]
It just prints "ok" and nothing else, but you're actually right in that I haven't updated. I forgot my config points at the plugin in my local directory rather than the system install 🤦. Both of the recent issues seem to be fixed now so thank you for the help
